### ISSUE TITLE
请问一下hexo 的主题 怎么修改 文章 的 margin padding 的 我改了 不生效

### ISSUE THREAD

**Issue by Zirpon** [yiluyanxia/hexo-theme-antiquity#4]
请问一下hexo 的主题 怎么修改 文章 的 margin padding 的 我改了 不生效

**Comment by yiluyanxia** [comment]
> 请问一下hexo 的主题 怎么修改 文章 的 margin padding 的 我改了 不生效

直接改css啊

**Comment by Zirpon** [comment]
我用beantech 的主题 然后改了 他的 themes/beantech/source/css/bootstrap.css
发现没生效 然后删掉 boostrap.min.css
然后 运行 hexo server 看效果
结果全是乱乱的

**Comment by Zirpon** [comment]
我想把他的文章 宽度 改成 跟你 主题 宽度 一样样的

**Comment by Zirpon** [comment]
他的宽度太小 文章不好看

**Comment by Zirpon** [comment]
这个 https://github.com/YenYuHsuan/hexo-theme-beantech

**Comment by yiluyanxia** [comment]
> 我用beantech 的主题 然后改了 他的 themes/beantech/source/css/bootstrap.css
> 发现没生效 然后删掉 boostrap.min.css
> 然后 运行 hexo server 看效果
> 结果全是乱乱的

不是很理解你在讲什么 = =，

**Comment by Zirpon** [comment]
就是 beantech 的主题

**Comment by yiluyanxia** [comment]
> 就是 beantech 的主题

那你问beantech的作者😂

**Comment by Zirpon** [comment]
我感觉 原理是一样的 其实 我就是不知道 hexo server 启动以后 访问 localhost:4000 实际上使用的是不是 bootstrap.css 但是我又不知道怎么生成 bootstrap.min.css

**Comment by Zirpon** [comment]
我感觉 实际上访问的 是bootstrap.min.css

**Comment by Zirpon** [comment]
但是 我改了 bootstrap.css 以后 不知道怎么生成 bootstrap.min.css

**Comment by Zirpon** [comment]
我想 你都能自己 写 出 一个主题 来 应该是很牛逼的了 应该知道 这个原理 又看到 你活跃度高 所以就尝试一下问问你了

**Comment by yiluyanxia** [comment]
哪有这么复杂，直接写几个样式覆盖一下原来的就好了。

**Comment by Zirpon** [comment]
> 哪有这么复杂，直接写几个样式覆盖一下原来的就好了。

**Comment by Zirpon** [comment]
我发现原来 他主题是用了 jekyll grunt 做的 https://github.com/Huxpro/huxpro.github.io

**Comment by Zirpon** [comment]
老哥 你懂 jekyll grunt 吗
