### ISSUE TITLE
_config.yml 文件hexo g时报错

### ISSUE THREAD

**Issue by cloudser** [yiluyanxia/hexo-theme-antiquity#9]
执行 ```$ hexo g``` 时，抛出下面的错误
```
YAMLException: duplicated mapping key at line 65, column 1:
    favicon: /images/default-avatar.webp
```
是_config.yml里关于favicon的映射出现了两次

**Comment by guanpingtang** [comment]
我也是在执行hexo g时抛出了一系列错误。我截取了其中3个
`duplicated mapping key at line 65, column 1:
    favicon: /images/default-avatar.webp`

```ERROR /Users/tgp/blog/themes/antiquity/layout/post.ejs:1
 >> 1| <%- partial('_partial/article', {post: page, index: false}) %>

/Users/tgp/blog/themes/antiquity/layout/_partial/article.ejs:40
    38|   <% if (!index){ %>
    39|     <%- partial('post/nav') %>
 >> 40|     <%- partial('gitment') %>
    41|   <% } %>
    42|
    43| </article>

/Users/tgp/blog/themes/antiquity/layout/_partial/gitment.ejs:7
    5| <script>
    6| var gitment = new Gitment({
 >> 7|   owner: '<%= theme.gitment.owner %>',
    8|   repo: '<%= theme.gitment.repo %>',
    9|   oauth: {
    10|     client_id: '<%= theme.gitment.client_id %>',

**Cannot read property 'owner' of undefined**```

```ERROR /Users/tgp/blog/themes/antiquity/layout/layout.ejs:13
    11|       <div id="middlecontent" title class="global-width sidebar-<%= theme.sidebar %>">
    12|         <section id="main"><%- body %></section>
 >> 13|         <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %>
    14|       </div>
    15|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
    16|       <%- partial('_partial/after-footer') %>

/Users/tgp/blog/themes/antiquity/layout/_partial/sidebar.ejs:2
    1| <aside id="sidebar">
 >> 2|   <% theme.widgets.forEach(function(widget){ %>
    3|     <%- partial('_widget/' + widget) %>
    4|   <% }) %>
    5| </aside>

**Cannot read property 'forEach' of undefined**```

请问作者可以修复一下吗？很喜欢这个主题，希望可以用上，感谢

**Comment by thirteenthree** [comment]
@我觉得可能是作者使用了某个插件,没有说明白,我也是这样的问题
#

**Comment by thirteenthree** [comment]
> 我也是在执行hexo g时抛出了一系列错误。我截取了其中3个
> `duplicated mapping key at line 65, column 1: favicon: /images/default-avatar.webp`
> 
> ```
>  >> 1| <%- partial('_partial/article', {post: page, index: false}) %>
> 
> /Users/tgp/blog/themes/antiquity/layout/_partial/article.ejs:40
>     38|   <% if (!index){ %>
>     39|     <%- partial('post/nav') %>
>  >> 40|     <%- partial('gitment') %>
>     41|   <% } %>
>     42|
>     43| </article>
> 
> /Users/tgp/blog/themes/antiquity/layout/_partial/gitment.ejs:7
>     5| <script>
>     6| var gitment = new Gitment({
>  >> 7|   owner: '<%= theme.gitment.owner %>',
>     8|   repo: '<%= theme.gitment.repo %>',
>     9|   oauth: {
>     10|     client_id: '<%= theme.gitment.client_id %>',
> 
> **Cannot read property 'owner' of undefined**```
> 
> ```ERROR /Users/tgp/blog/themes/antiquity/layout/layout.ejs:13
>     11|       <div id="middlecontent" title class="global-width sidebar-<%= theme.sidebar %>">
>     12|         <section id="main"><%- body %></section>
>  >> 13|         <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %>
>     14|       </div>
>     15|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
>     16|       <%- partial('_partial/after-footer') %>
> 
> /Users/tgp/blog/themes/antiquity/layout/_partial/sidebar.ejs:2
>     1| <aside id="sidebar">
>  >> 2|   <% theme.widgets.forEach(function(widget){ %>
>     3|     <%- partial('_widget/' + widget) %>
>     4|   <% }) %>
>     5| </aside>
> 
> **Cannot read property 'forEach' of undefined**```
> 
> 请问作者可以修复一下吗？很喜欢这个主题，希望可以用上，感谢
> ```

你好,我遇见和你一样的问题,刚开始我也是挺着急的,没有仔细看,"duplicated mapping key at line 65, column 1: favicon: /images/default-avatar.webp"错误提示是:在65行这句话重复了,你打开themes主题的config文件 第42行与第65行是一样的,你删除一个就行了,可能是作者不小心的

**Comment by guanpingtang** [comment]
> > 我也是在执行hexo g时抛出了一系列错误。我截取了其中3个
> > `duplicated mapping key at line 65, column 1: favicon: /images/default-avatar.webp`
> > ```
> >  >> 1| <%- partial('_partial/article', {post: page, index: false}) %>
> > 
> > /Users/tgp/blog/themes/antiquity/layout/_partial/article.ejs:40
> >     38|   <% if (!index){ %>
> >     39|     <%- partial('post/nav') %>
> >  >> 40|     <%- partial('gitment') %>
> >     41|   <% } %>
> >     42|
> >     43| </article>
> > 
> > /Users/tgp/blog/themes/antiquity/layout/_partial/gitment.ejs:7
> >     5| <script>
> >     6| var gitment = new Gitment({
> >  >> 7|   owner: '<%= theme.gitment.owner %>',
> >     8|   repo: '<%= theme.gitment.repo %>',
> >     9|   oauth: {
> >     10|     client_id: '<%= theme.gitment.client_id %>',
> > 
> > **Cannot read property 'owner' of undefined**```
> > 
> > ```ERROR /Users/tgp/blog/themes/antiquity/layout/layout.ejs:13
> >     11|       <div id="middlecontent" title class="global-width sidebar-<%= theme.sidebar %>">
> >     12|         <section id="main"><%- body %></section>
> >  >> 13|         <%- partial('_partial/sidebar', null, {cache: !config.relative_link}) %>
> >     14|       </div>
> >     15|       <%- partial('_partial/footer', null, {cache: !config.relative_link}) %>
> >     16|       <%- partial('_partial/after-footer') %>
> > 
> > /Users/tgp/blog/themes/antiquity/layout/_partial/sidebar.ejs:2
> >     1| <aside id="sidebar">
> >  >> 2|   <% theme.widgets.forEach(function(widget){ %>
> >     3|     <%- partial('_widget/' + widget) %>
> >     4|   <% }) %>
> >     5| </aside>
> > 
> > **Cannot read property 'forEach' of undefined**```
> > 
> > 请问作者可以修复一下吗？很喜欢这个主题，希望可以用上，感谢
> > ```
> 
> 你好,我遇见和你一样的问题,刚开始我也是挺着急的,没有仔细看,"duplicated mapping key at line 65, column 1: favicon: /images/default-avatar.webp"错误提示是:在65行这句话重复了,你打开themes主题的config文件 第42行与第65行是一样的,你删除一个就行了,可能是作者不小心的

非常感谢，已经好了。细心的你定会被温柔相待。

**Comment by yiluyanxia** [comment]
已修复
